apiVersion: apps/v1
kind: Deployment             #Deployment create = replication set + pods+ cont+application
metadata:
  name: my-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soil
  template:
    metadata:
      labels:
        app: soil
    spec:
      containers:
        - name: cont1
          image: chaithanya2/soil:latest
          ports:
            - containerPort: 80

  # deployment = roolback features and 0 down time it has also version features to track so deployment has more advance features
  # replication set = pods+ cont + app
