apiVersion: v1                      # service file must expose to pods 
kind: Service                       # service file
metadata:
  name: soil
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: soil
  ports:
    - protocol: TCP
      port: 80        # LoadBalancer external port
      targetPort: 80  # Must match containerPort
